// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users
(id, email, role, password_hash)
VALUES
($1, $2, $3, $4)
RETURNING id
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	Role         UserRole    `json:"role"`
	PasswordHash string      `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.PasswordHash,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
